[project]
name = "promptmanager"
description = "A powerful ComfyUI custom node that extends the standard text encoder with persistent prompt storage, advanced search capabilities, and an automatic image gallery system using SQLite."
version = "3.3.0"
license = {file = "LICENSE"}
requires-python = ">=3.10"
dependencies = ["watchdog>=2.1.0", "Pillow>=8.0.0"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project.urls]
Repository = "https://github.com/ComfyAssets/ComfyUI_PromptManager"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "kiko9"
DisplayName = "ComfyUI_PromptManager"
Icon = "https://avatars.githubusercontent.com/u/213204677?s=200"

[tool.black]
line-length = 88
target-version = ["py310"]

[tool.bandit]
exclude_dirs = ["tests", "reference"]
